CREATE TABLE IF NOT EXISTS PIPassageiro (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    senha VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PIPonto (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PIRota (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    pontoInicial INT NOT NULL,
    pontoFinal INT NOT NULL,
    FOREIGN KEY (pontoInicial) REFERENCES PIPonto (id),
    FOREIGN KEY (pontoFinal) REFERENCES PIPonto (id)
);