-- CREATE TABLE IF NOT EXISTS categorias (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     nome varchar(255) NOT NULL,
--     descricao varchar(255) NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS tarefas (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     titulo varchar(255) NOT NULL,
--     descricao varchar(255) NOT NULL,
--     categoriaId INT NOT NULL,
--     prazo DATE NOT NULL,
--     FOREIGN KEY (categoriaId) REFERENCES categorias(id)
-- );